#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin

# Change directory to root's home
cd ~root || exit 1

# Generate a strong, random password
password=$(head -c 18 /dev/random | base64) || exit 2

# Run MySQL's secure-installation script, applying all hardening
# measures and supplying the new root password where necessary. (Using
# a here-document rather than 'echo' keeps $password from appearing in
# the process list.)
mysql_secure_installation <<EOF || exit 3

Y
$password
$password
Y
Y
Y
Y
EOF

# Save the password in root's .my.cnf
umask 077 && cat >.my.cnf <<EOF || exit 4
[client]
password=$password
EOF

exit 0
