---
- hosts: drupal-sl
  user: vagrant
  sudo: True

  vars:
    home_directory: /home/${user} 
    proxy_server: proxy.tchpc.tcd.ie
    proxy_port: 8080

  vars_files:                                                                   
    - global_vars.yml

  tasks:

  - name: install pip
    shell: http_proxy=http://proxy.tchpc.tcd.ie:8080 easy_install pip

  - name: easy_install -U distribute 
    shell: http_proxy=${proxy_server}:${proxy_port} easy_install -U distribute

  - name: /root/.pip
    file: path=/root/.pip/ owner=root  mode=0755 state=directory

  - name: write /root/.pip/pip.conf
    action: template src=templates/pip.j2 dest=/root/.pip/pip.conf owner=root
    tags: configuration

    # - name: /home/vagrant/.pip
    #   file: path=/home/vagrant/.pip/ owner=vagrant group=vagrant  mode=0755 state=directory

    # - name: write /home/vagrant/.pip/pip.conf
    #   action: template src=templates/pip.j2 dest=/home/vagrant/.pip/pip.conf owner=vagrant
    #   tags: configuration




