---
- hosts: all
  user: vagrant
  sudo: True

  vars:
    proxy_server: gateway.tchpc.tcd.ie
    proxy_port: 8080
    socks_server: 134.226.112.43
    socks_port: 1080

  vars_files:
    - global_vars.yml

  tasks:
  - name: write /etc/profile.d/proxy.sh
    action: template src=templates/proxy.j2 dest=/etc/profile.d/proxy.sh
    tags: configuration

  - name: Ubuntu | configure apt to use a proxy
    action: template src=templates/apt.j2 dest=/etc/apt/apt.conf
    only_if: '$is_ubuntu'
    tags: configuration

  - name: Scientific | configure yum to use a proxy
    action: template src=templates/yum.j2 dest=/etc/yum.conf
    only_if: '$is_scientific'
    tags: configuration

  - name: Ubuntu | install python-software-properties and python-apt
    action: apt pkg=$item state=installed update_cache=yes
    only_if: '$is_ubuntu'
    with_items:
      - python-software-properties
      - python-apt
    tags: packages

  - name: Ubuntu | install tsocks
    action: apt name=$item state=installed
    only_if: '$is_ubuntu'
    with_items:
      - tsocks
    tags: packages

  - name: Ubuntu | configure tsocks
    action: template src=templates/tsocks.j2 dest=/etc/tsocks.conf
    only_if: '$is_ubuntu'
    tags: configuration

  - name: configure curlrc for root
    action: template src=templates/curlrc.j2 dest=/root/.curlrc
    tags: configuration

  - name: configure gemrc for root
    action: template src=templates/gemrc.j2 dest=/root/.gemrc
    tags: configuration

  - name: Ubuntu | configure wgetrc for the system
    action: template src=templates/wgetrc.j2 dest=/etc/wgetrc
    only_if: '$is_ubuntu'
    tags: configuration
