---
- hosts: webservers-ubuntu;kraken-ubuntu
  user: vagrant

  vars_files:                                                                   
    - global_vars.yml

  tasks:

  - include: ./rvm-setup-ubuntu.yml
  - include: ./rvm-setup-common.yml

  - name: install rails
    action: shell .rvm/bin/gem install rails

  - name: install unicorn
    action: shell .rvm/bin/gem install unicorn
