---
  - name: Ubuntu | set up rvm
    sudo: True
    action: apt pkg=$item state=present
    only_if: '$is_ubuntu'
    with_items:
      - build-essential
      - openssl
      - libreadline6
      - libreadline6-dev
      - curl
      - git-core
      - zlib1g
      - zlib1g-dev
      - libssl-dev
      - libyaml-dev
      - libsqlite3-dev
      - sqlite3
      - libxml2-dev
      - libxslt1-dev
      - autoconf
      - libc6-dev
      - libncurses5-dev
      - automake
      - libtool
      - bison
      - subversion

  - name: Scientific | set up rvm
    sudo: True
    action: yum pkg=$item state=present
    only_if: '$is_scientific'
    with_items:
      - bzip2
      - cpio
      - expat-devel
      - gcc
      - gcc-c++
      - gettext-devel
      - git
      - libcurl-devel
      - libxml2
      - libxml2-devel
      - libxslt
      - libxslt-devel
      - mailx
      - make
      - openssl-devel
      - patch
      - perl
      - readline-devel
      - sendmail
      - wget
      - which
      - zlib-devel

  - name: configure curlrc for vagrant                                           
    action: template src=templates/curlrc.j2 dest=/home/vagrant/.curlrc                 
    tags: configuration                                                         

  - name: install rvm
    action: shell curl -L https://get.rvm.io | bash -s stable creates=/home/vagrant/.rvm/

  - name: install ruby 1.9.3
    action: shell .rvm/bin/rvm install 1.9.3

  - name: use ruby 1.9.3 by default
    action: shell .rvm/bin/rvm alias create default ruby-1.9.3-p286

  - name: install facter
    action: shell .rvm/bin/gem install facter

  - name: install ohai
    action: shell .rvm/bin/gem install ohai
