---
#  - name: configure curlrc for vagrant                                           
#    action: template src=templates/curlrc.j2 dest=/home/vagrant/.curlrc                 
#    tags: configuration                                                         

  - name: install rvm
    action: shell curl -L https://get.rvm.io | bash -s stable creates=/home/vagrant/.rvm/

  - name: install ruby 1.9.3
    action: shell .rvm/bin/rvm install 1.9.3

  - name: use ruby 1.9.3 by default
    action: shell .rvm/bin/rvm use 1.9.3 --default

  - name: install facter
    action: shell .rvm/bin/gem install facter

  - name: install ohai
    action: shell .rvm/bin/gem install ohai
