---
- hosts: web-servers
  user: vagrant
  vars:
    home_directory: /home/${user} 
  tasks:
  - name: set up rvm
    sudo: True
    action: apt pkg=$item state=present
    with_items:
      - build-essential
      - openssl
      - libreadline6
      - libreadline6-dev
      - curl
      - git-core
      - zlib1g
      - zlib1g-dev
      - libssl-dev
      - libyaml-dev
      - libsqlite3-dev
      - sqlite3
      - libxml2-dev
      - libxslt1-dev
      - autoconf
      - libc6-dev
      - libncurses5-dev
      - automake
      - libtool
      - bison
      - subversion
  - name: install rvm
    action: shell curl -L https://get.rvm.io | bash -s stable creates=${home_directory}/.rvm/
