---
- hosts: rvm
  user: vagrant
  vars:
    home_directory: /home/${user} 
  tasks:
  - name: set up rvm
    sudo: True
    action: apt pkg=$item state=present update_cache=yes
    with_items:
      - build-essential
      - openssl
      - libreadline6
      - libreadline6-dev
      - curl
      - git-core
      - zlib1g
      - zlib1g-dev
      - libssl-dev
      - libyaml-dev
      - libsqlite3-dev
      - sqlite3
      - libxml2-dev
      - libxslt1-dev
      - autoconf
      - libc6-dev
      - libncurses5-dev
      - automake
      - libtool
      - bison
      - subversion
  - name: install rvm
    action: shell curl -L https://get.rvm.io | bash -s stable creates=${home_directory}/.rvm/
  - name: install ruby 1.9.3
    action: shell .rvm/bin/rvm install 1.9.3
  - name: rvm use ruby 1.9.3 by default
    action: shell .rvm/bin/rvm alias create default ruby-1.9.3-p286
  - name: install rails
    action: shell .rvm/bin/gem install rails
