---
- hosts: ceph
  user: vagrant
  sudo: True

  tasks:

  - name: install the python-software-properties to get apt-add-repository
    action: apt pkg=python-software-properties state=latest update-cache=yes

  - name: get the public key for ceph repo
    shell: wget -q -O- https://raw.github.com/ceph/ceph/master/keys/release.asc | apt-key add -

  - name: configure the ceph apt repository
    apt_repository: repo='deb http://eu.ceph.com/debian/ $(lsb_release -sc) main'

  - name: install the latest version of ceph
    action: apt pkg=ceph state=latest update-cache=yes

  - name: authorized_keys for root
    authorized_key: user=root key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" state=present
    
  - name: install insecure private key for root
    action: copy src=files/insecure_private_key dest=/root/.ssh/id_rsa owner=root group=root mode=0600
  - name: install insecure config for root
    action: copy src=files/insecure_config dest=/root/.ssh/config owner=root group=root mode=0600

  - name: authorized_keys for vagrant
    authorized_key: user=vagrant key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" state=present
    
  - name: install insecure private key for vagrant
    action: copy src=files/insecure_private_key dest=/home/vagrant/.ssh/id_rsa owner=vagrant group=vagrant mode=0600

  - name: install insecure config for vagrant
    action: copy src=files/insecure_config dest=/home/vagrant/.ssh/config owner=vagrant group=vagrant mode=0600
